CREATE TABLE IF NOT EXISTS folders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE reference_documents ADD COLUMN folder_id INTEGER REFERENCES folders(id) ON DELETE SET NULL;
